const Map<String, String> leagueToCompetitionId = {
  'Premier League': 'GB1',
  'La Liga': 'ES1',
  'Serie A': 'IT1',
  'Bundesliga': 'L1',
  'Ligue 1': 'FR1',
  'Liga Portugal': 'PO1',
  'Süper Lig': 'TR1',
  'Eredivisie': 'NL1',
  'Jupiler Pro League': 'BE1',
  'Super League 1': 'GR1',
  'Scottish Premiership': 'SC1',
  'Ukrainian Premier Liga': 'UKR1',
  'Superliga': 'DK1',
  'Super League Switzerland': 'C1',
  'Austrian Bundesliga': 'A1',
  'Ligat ha\'Al': 'ISR1',
  'PKO BP Ekstraklasa': 'PL1',
  'Allsvenskan': 'SE1',
  'Campeonato Brasileiro': 'BRA1',
  'Liga MX': 'MEX1',
  'Championship': 'GB2',
  'Major League Soccer': 'MLS1',
  'J1 League': 'JAP1',
  'Ligue 2': 'FR2',
  'Serie B': 'IT2',
  'Bundesliga 2': 'L2',
  'A-League Men': 'AUS1',
  'Chinese Super League': 'CSL',
  'USL Championship': 'USL',
};
final List<String> leagues = [
  'Championship',
  'LaLiga2',
  'Serie B',
  'Bundesliga 2',
  'Keuken Kampioen Divisie',
  'Fortuna 1 Liga',
  'Lig 1',
  'Superettan',
  'OBOS-ligaen',
  'Prva liga Srbije',
  'Scottish Championship',
  'Ykkönen',
  'Vtora Liga',
  'Persha Liga',
  'Prva liga FBiH',
  'Lengjudeild',
  'Challenge League',
  'Nakotnes liga',
  'Esiliiga',
];
